Repository 3-isekaiSSG/isekai-fe, pull requests merged in 2024-04, with the labels that each got.

#125 Feat: 비회원 장바구니 담기
  src/components/ProductsOption/NoOption.tsx
  src/components/ProductsOption/OptionCheck.tsx
  src/components/ProductsOption/OptionComponents.tsx
  src/components/ProductsOption/OptionDepthModal.tsx
  src/components/ProductsOption/OptionModal.tsx
  src/components/products/BottomBtn.tsx
  src/states/optionAtom.ts
  src/types/productDataType.ts
Labels: 📬 API

#127 Feature/option
  src/components/AppBar/GoToCart.tsx
  src/components/ProductsOption/NoOption.tsx
  src/components/products/BottomBtn.tsx
  src/components/products/ProductHeader.tsx
  src/states/optionAtom.ts
  src/utils/cartApi.ts
Labels: ✨ Feature, 📬 API

#131 Feat: 상품 옵션 추가 구현 및 credential 수정
  src/components/ProductsOption/OptionCheck.tsx
  src/components/ProductsOption/OptionDepthModal.tsx
  src/components/products/BottomBtn.tsx
  src/states/optionAtom.ts
  src/types/OptionType.ts
Labels: 🎨 Html&css, ✨ Feature, 📬 API

#132 비회원 장바구니 쿠키 테스트
  src/components/ProductsOption/OptionCheck.tsx
  src/components/ProductsOption/OptionDepthModal.tsx
  src/components/products/BottomBtn.tsx
  src/states/optionAtom.ts
  src/types/OptionType.ts
Labels: 📬 API

#134 Fix: carts에 include 추가
  src/app/cart/page.tsx
  src/components/AppBar/GoToCart.tsx
  src/components/AppBar/MallBtn.tsx
  src/components/AppBar/index.tsx
  src/components/AppBar/state.ts
  src/components/Buttons/GetCartBtn.tsx
  src/components/ProductCard/TwoProductCard.tsx
  src/components/ProductsOption/OptionCheck.tsx
  src/components/Toast.tsx
  src/components/products/BottomBtn.tsx
  src/components/ui/OneItemBundleList.tsx
  src/components/ui/TwoItemBundleList.tsx
  src/containers/cart/CartItemCard.tsx
  src/containers/cart/CartItems.tsx
  src/containers/cart/DeleteButton.tsx
  src/states/optionAtom.ts
  src/styles/animations.css
  src/types/cartType.ts
  src/utils/cartApi.ts
  src/utils/optionApi.ts
Labels: 🎨 Html&css, ✨ Feature, 📬 API

#138 Fix: 회원가입 로직 변경
  src/containers/join-email/EasyForm.tsx
  src/containers/join-form/JoinForm.tsx
Labels: 🐞 BugFix, ✨ Feature, 📬 API

#142 빌드 테스트
  src/app/api/auth/[...nextauth]/options.ts
  src/containers/join-email/EasyForm.tsx
  src/containers/join-form/JoinForm.tsx
  src/containers/login/LoginForm.tsx
  src/types/next-auth.d.ts
Labels: 🌏 Deploy

#143 Feat: 리다이렉트, 미들웨어(?) 설정
  src/app/(member)/find-id-result/page.tsx
  src/app/(member)/find-idpw/page.tsx
  src/app/(member)/join-agree/page.tsx
  src/app/(member)/join-auth/page.tsx
  src/app/(member)/join-email/page.tsx
  src/app/(member)/join-form/page.tsx
  src/app/(member)/join-intro/page.tsx
  src/app/(member)/login/page.tsx
  src/app/(member)/my-clip/page.tsx
  src/app/(member)/non-login/page.tsx
  src/app/(member)/non-order/page.tsx
  src/app/(member)/pw-reset/page.tsx
  src/containers/login/LoginForm.tsx
  src/containers/login/SocialLoginForm.tsx
  src/middleware.ts
Labels: 🐞 BugFix, ✨ Feature, 📬 API

#144 Feature/cart option
  src/app/(main)/category/[...categoryName]/page.tsx
  src/app/(member)/login/page.tsx
  src/app/(products)/products/[code]/page.tsx
  src/app/(products)/products/[code]/write-review/page.tsx
  src/app/cart/page.tsx
  src/components/AppBar/GoToCart.tsx
  src/components/AppBar/index.tsx
  src/components/Buttons/GetCartBtn.tsx
  src/components/Footer/index.tsx
  src/components/ProductsOption/NoOption.tsx
  src/components/ProductsOption/OptionCheck.tsx
  src/components/ProductsOption/OptionComponents.tsx
  src/components/ProductsOption/OptionDepthModal.tsx
  src/components/ProductsOption/productsOption.module.css
  src/components/products/BottomBtn.tsx
  src/components/products/CategoryPreview.tsx
  src/components/products/ProductHeader.tsx
  src/containers/cart/AllSelectHeader.tsx
  src/containers/cart/CartCardWrapper.tsx
  src/containers/cart/CartItemCard.tsx
  src/containers/cart/CartItems.tsx
  src/containers/cart/DeleteButton.tsx
  src/containers/cart/DeliveryTypeSelect.tsx
  src/containers/cart/ItemInputCheckBox.tsx
  src/containers/cart/NoCart.tsx
  src/containers/cart/ToolBar.tsx
  src/containers/cart/UpdateCartCount.tsx
  src/containers/cart/UserDeliveryAddress.tsx
  src/containers/cart/action.ts
  src/containers/cart/cart.module.css
  src/containers/login/NonArea.tsx
  src/containers/order/OrderCards.tsx
  src/containers/order/OrderProduct.tsx
  src/containers/order/OrderToolBar.tsx
  src/containers/order/order.module.css
  src/states/cartAtom.ts
  src/states/optionAtom.ts
  src/states/orderAtom.ts
  src/types/orderType.ts
  src/types/productDataType.ts
  src/utils/addCartApi.ts
  src/utils/calculateTotalPrice.ts
  src/utils/cartApi.ts
  src/utils/productDataApi.ts
Labels: 🎨 Html&css, ✨ Feature, 📬 API

#145 프로덕션 빌드
  src/app/(main)/category/[...categoryName]/page.tsx
  src/app/(member)/find-id-result/page.tsx
  src/app/(member)/find-idpw/page.tsx
  src/app/(member)/join-agree/page.tsx
  src/app/(member)/join-auth/page.tsx
  src/app/(member)/join-email/page.tsx
  src/app/(member)/join-form/page.tsx
  src/app/(member)/join-intro/page.tsx
  src/app/(member)/login/page.tsx
  src/app/(member)/my-clip/page.tsx
  src/app/(member)/non-login/page.tsx
  src/app/(member)/non-order/page.tsx
  src/app/(member)/pw-reset/page.tsx
  src/app/(products)/products/[code]/page.tsx
  src/app/(products)/products/[code]/write-review/page.tsx
  src/app/cart/page.tsx
  src/components/AppBar/GoToCart.tsx
  src/components/AppBar/index.tsx
  src/components/Buttons/GetCartBtn.tsx
  src/components/Footer/index.tsx
  src/components/ProductsOption/NoOption.tsx
  src/components/ProductsOption/OptionCheck.tsx
  src/components/ProductsOption/OptionComponents.tsx
  src/components/ProductsOption/OptionDepthModal.tsx
  src/components/ProductsOption/productsOption.module.css
  src/components/products/BottomBtn.tsx
  src/components/products/CategoryPreview.tsx
  src/components/products/ProductHeader.tsx
  src/containers/cart/AllSelectHeader.tsx
  src/containers/cart/CartCardWrapper.tsx
  src/containers/cart/CartItemCard.tsx
  src/containers/cart/CartItems.tsx
  src/containers/cart/DeleteButton.tsx
  src/containers/cart/DeliveryTypeSelect.tsx
  src/containers/cart/ItemInputCheckBox.tsx
  src/containers/cart/NoCart.tsx
  src/containers/cart/ToolBar.tsx
  src/containers/cart/UpdateCartCount.tsx
  src/containers/cart/UserDeliveryAddress.tsx
  src/containers/cart/action.ts
  src/containers/cart/cart.module.css
  src/containers/login/LoginForm.tsx
  src/containers/login/NonArea.tsx
  src/containers/login/SocialLoginForm.tsx
  src/containers/order/OrderCards.tsx
  src/containers/order/OrderProduct.tsx
  src/containers/order/OrderToolBar.tsx
  src/containers/order/order.module.css
  src/middleware.ts
  src/states/cartAtom.ts
  src/states/optionAtom.ts
  src/states/orderAtom.ts
  src/types/orderType.ts
  src/types/productDataType.ts
  src/utils/addCartApi.ts
  src/utils/calculateTotalPrice.ts
  src/utils/cartApi.ts
  src/utils/productDataApi.ts
Labels: 🌏 Deploy

#146 Fix: 비회원 빈 데이터 지정
  src/app/cart/page.tsx
Labels: 🐞 BugFix

#147 Fix: 비회원 빈 데이터 지정
  src/app/cart/page.tsx
Labels: 🐞 BugFix

#148 Fix: 옵션 미선택 토스트
  src/components/Toast.tsx
  src/components/products/BottomBtn.tsx
Labels: 🐞 BugFix

#149 Feature/review
  src/app/(member)/myssg/page.tsx
  src/app/(products)/products/[code]/page.tsx
  src/app/(products)/products/[code]/reviews/page.tsx
  src/components/ProductsOption/NoOption.tsx
  src/components/products/ReviewPreview.tsx
  src/components/reviews/ReviewAllList.tsx
  src/components/reviews/ReviewPhoto.tsx
  src/components/reviews/ReviewStar.tsx
  src/components/reviews/reviews.module.css
  src/containers/myssg/BenefitCarousel.tsx
  src/containers/myssg/CouponCarousel.tsx
  src/containers/myssg/MyProfile.tsx
  src/containers/myssg/OrderCheck.tsx
  src/containers/myssg/myssg.module.css
  src/types/ReviewType.ts
Labels: 🎨 Html&css, ✨ Feature, 📬 API

#151 Feature/cart nonmember
  src/components/Buttons/GetCartBtn.tsx
  src/components/ProductsOption/NoOption.tsx
  src/components/products/BottomBtn.tsx
  src/utils/addCartApi.ts
  src/utils/addCartMemberApi.ts
  src/utils/addCartNonMemberApi.ts
Labels: 🐞 BugFix

#153 Fix: 비회원 장바구니 수정
  src/app/cart/page.tsx
  src/components/AppBar/GoToCart.tsx
  src/utils/addCartNonMemberApi.ts
Labels: 🐞 BugFix, 📬 API

#154 비회원 장바구니 테스트
  src/app/cart/page.tsx
  src/components/AppBar/GoToCart.tsx
  src/utils/addCartNonMemberApi.ts
Labels: 🌏 Deploy

#155 Fix: 비회원 장바구니 client 수정
  src/app/cart/page.tsx
  src/containers/cart/NonMemberCart.tsx
  src/containers/cart/UserDeliveryAddress.tsx
  src/utils/cartApi.ts
Labels: 🐞 BugFix

#156 비회원 장바구니 테스트
  src/app/cart/page.tsx
  src/containers/cart/NonMemberCart.tsx
  src/containers/cart/UserDeliveryAddress.tsx
  src/utils/cartApi.ts
Labels: 🌏 Deploy

#157 HotFix: 비회원 장바구니 에러잡기
  src/app/cart/page.tsx
Labels: 🐞 BugFix

#158 Fix: 비회원 장바구니 에러잡기
  src/app/cart/page.tsx
Labels: 🐞 BugFix

#159 Fix: 에러 로그 작성
  src/containers/cart/AllSelectHeader.tsx
  src/containers/cart/NonMemberCart.tsx
Labels: 🐞 BugFix

#160 Fix: 에러 로그 작성
  src/containers/cart/AllSelectHeader.tsx
  src/containers/cart/NonMemberCart.tsx
Labels: 🐞 BugFix

#161 Fix: 비회원 client 컴포넌트 추가
  src/containers/cart/CartItemCardClient.tsx
  src/containers/cart/ItemInputCheckBox.tsx
  src/containers/cart/NonMemberCart.tsx
Labels: 🐞 BugFix

#162 Feat: 주석 해제 및 비회원 주문하기 페이지 이동
  src/containers/cart/AllSelectHeader.tsx
  src/containers/cart/NonMemberCart.tsx
  src/containers/login/NonArea.tsx
Labels: 🐞 BugFix

#163 Hotfix/cart nonmember
  src/components/products/BottomBtn.tsx
  src/containers/cart/AllSelectHeader.tsx
  src/containers/cart/CartItemCardClient.tsx
  src/containers/cart/DeleteButton.tsx
  src/containers/cart/ItemInputCheckBox.tsx
  src/containers/cart/NonMemberCart.tsx
  src/containers/login/NonArea.tsx
Labels: 🐞 BugFix

#164 Fix: 비회원 장바구니 삭제 테스트
  src/components/products/BottomBtn.tsx
  src/containers/cart/CartItemCardClient.tsx
  src/containers/cart/DeleteButton.tsx
Labels: 🐞 BugFix

#165 Fix: 비회원 장바구니 수량 추가 제거
  src/containers/cart/NonMemberCart.tsx
  src/containers/cart/UpdateCartCount.tsx
Labels: 🐞 BugFix, 📬 API

#166 Fix: 비회원 cart 데이터 수정
  src/containers/cart/NonMemberCart.tsx
  src/states/cartAtom.ts
Labels: 🐞 BugFix

#167 Fix: 무한 루프 삭제
  src/containers/cart/NonMemberCart.tsx
Labels: 🐞 BugFix

#168 Fix: 장바구니 수량 추가제거 비동기 처리
  src/containers/cart/CartItemCardClient.tsx
  src/containers/cart/UpdateCartCount.tsx
Labels: 🐞 BugFix, 📬 API

#169 Hotfix/cart nonmember
  src/containers/cart/CartItemCardClient.tsx
  src/containers/cart/NonMemberCart.tsx
  src/containers/cart/UpdateCartCount.tsx
  src/states/cartAtom.ts
Labels: 🐞 BugFix, 📬 API

#170 Feat: 공유 모달 퍼블리싱 / 좋아요 페이지 퍼블리싱
  src/app/(member)/my-clip/page.tsx
  src/components/BundleList/OneItemBundleList.tsx
  src/components/BundleList/TwoItemBundleList.tsx
  src/components/Buttons/LikeBtn.tsx
  src/components/Buttons/ShareBtn.tsx
  src/components/ProductCard/TwoProductCard.tsx
  src/components/TabBar.tsx
  src/components/products/BottomBtn.tsx
  src/components/products/ProductSimple.tsx
  src/components/products/ShareModal.tsx
  src/components/products/state.ts
  src/containers/cart/NoCart.tsx
  src/containers/cart/NonMemberCart.tsx
  src/containers/cart/ToolBar.tsx
  src/containers/category/[categoryName]/CategoryNameHeader.tsx
  src/containers/my-clip/MyLikeFilter.tsx
  src/containers/my-clip/MyLikeFolder.tsx
  src/containers/my-clip/MyLikeItemArea.tsx
  src/containers/my-clip/MyLikeItemEdit.tsx
  src/containers/my-clip/MyLikeItemInfo.tsx
  src/containers/my-clip/MyLikeItemList.tsx
  src/containers/my-clip/Pagination.tsx
  src/containers/my-clip/mylike.module.css
  src/containers/my-clip/state.ts
  src/containers/myssg/states.ts
Labels: 🎨 Html&css, ✨ Feature, 📬 API

#172 Fix: 캐러셀 데이터 수정
  public/images/categoryL/1.png
  public/images/categoryL/10.png
  public/images/categoryL/11.png
  public/images/categoryL/12.png
  public/images/categoryL/2.png
  public/images/categoryL/3.png
  public/images/categoryL/4.png
  public/images/categoryL/5.png
  public/images/categoryL/6.png
  public/images/categoryL/7.png
  public/images/categoryL/8.png
  public/images/categoryL/9.png
  public/images/categoryL/_10.png
  public/images/isekai.png
  public/images/isekai2.png
  public/images/isekai3.png
  src/app/@modal/(...)search/modal.tsx
  src/app/@modal/(...)search/page.tsx
  src/containers/home/carouselState.ts
Labels: 🎨 Html&css

#175 Feature/bundles
  src/app/(main)/(home)/special-price/page.tsx
  src/components/BundleList/OneItemBundleList.tsx
  src/components/BundleList/TwoItemBundleList.tsx
  src/components/Buttons/GetCartBtn.tsx
  src/components/ProductCard/TwoProductCard.tsx
  src/components/special-price/SpecialAll.tsx
  src/components/special-price/SpecialSSG.tsx
  src/components/special-price/SpecialToday.tsx
  src/containers/home/SpecialItem.tsx
  src/containers/special-price/index.tsx
  src/types/BundleType.ts
  src/utils/bundleApi.ts
Labels: ✨ Feature, 📬 API

#176 Feat: 검색 결과 구현
  src/app/search/[searchItem]/page.tsx
  src/containers/search/NonSearch.tsx
  src/containers/search/[searchItem]/SearchResultItem.tsx
  src/types/productType.ts
Labels: 📬 API

#177 프로덕션 빌드
  public/images/categoryL/1.png
  public/images/categoryL/10.png
  public/images/categoryL/11.png
  public/images/categoryL/12.png
  public/images/categoryL/2.png
  public/images/categoryL/3.png
  public/images/categoryL/4.png
  public/images/categoryL/5.png
  public/images/categoryL/6.png
  public/images/categoryL/7.png
  public/images/categoryL/8.png
  public/images/categoryL/9.png
  public/images/categoryL/_10.png
  public/images/isekai.png
  public/images/isekai2.png
  public/images/isekai3.png
  src/app/(main)/(home)/special-price/page.tsx
  src/app/@modal/(...)search/modal.tsx
  src/app/@modal/(...)search/page.tsx
  src/app/search/[searchItem]/page.tsx
  src/components/BundleList/OneItemBundleList.tsx
  src/components/BundleList/TwoItemBundleList.tsx
  src/components/Buttons/GetCartBtn.tsx
  src/components/ProductCard/TwoProductCard.tsx
  src/components/special-price/SpecialAll.tsx
  src/components/special-price/SpecialSSG.tsx
  src/components/special-price/SpecialToday.tsx
  src/containers/home/SpecialItem.tsx
  src/containers/home/carouselState.ts
  src/containers/search/NonSearch.tsx
  src/containers/search/[searchItem]/SearchResultItem.tsx
  src/containers/special-price/index.tsx
  src/types/BundleType.ts
  src/types/productType.ts
  src/utils/bundleApi.ts
Labels: 🌏 Deploy

#183 Fix: Link 삭제
  src/components/BundleList/OneItemBundleList.tsx
Labels: ✨ Feature

#186 Feat: 로딩스피너 구현
  src/app/loading.tsx
  src/components/LoadingSpinner.tsx
Labels: 🎨 Html&css, ✨ Feature

#187 프로덕션 빌드
  src/app/(main)/category/[...categoryName]/page.tsx
  src/app/(member)/my-clip/page.tsx
  src/app/layout.tsx
  src/app/loading.tsx
  src/components/BundleList/OneItemBundleList.tsx
  src/components/Buttons/LikeBtn.tsx
  src/components/Header/state.ts
  src/components/KakaoScript/index.tsx
  src/components/LoadingSpinner.tsx
  src/components/ProductCard/TwoProductCard.tsx
  src/components/ProductCard/UpdateRank.tsx
  src/components/products/BottomBtn.tsx
  src/components/products/ProductSimple.tsx
  src/components/products/ShareModal.tsx
  src/containers/category/[categoryName]/CategoryLAll.tsx
  src/containers/category/[categoryName]/CategoryNameHeader.tsx
  src/containers/category/[categoryName]/LCategoryBest.tsx
  src/containers/my-clip/CategoryList.tsx
  src/containers/my-clip/MyLikeFilter.tsx
  src/containers/my-clip/MyLikeFolder.tsx
  src/containers/my-clip/MyLikeItemArea.tsx
  src/containers/my-clip/MyLikeItemEdit.tsx
  src/containers/my-clip/MyLikeItemList.tsx
  src/containers/my-clip/ProductCard.tsx
  src/containers/my-clip/ProductList.tsx
  src/containers/my-clip/SellerList.tsx
  src/containers/my-clip/mylike.module.css
  src/containers/my-clip/state.ts
  src/states/likeAtom.ts
  src/types/myClipType.ts
  src/utils/categoryProductQueryApi.ts
  src/utils/getClipApi.ts
  src/utils/kakaoShareApi.ts
Labels: 🌏 Deploy

#188 Feature/search scroll
  src/app/layout.tsx
  src/components/BundleList/OneItemBundleList.tsx
Labels: 🐞 BugFix, ✨ Feature

#189 fetch 데이터 확인을 위한 프로덕션 빌드
  src/app/layout.tsx
  src/components/BundleList/OneItemBundleList.tsx
Labels: 🌏 Deploy

#190 Fix: 번들 데이터 테스트 주석해제
  src/components/BundleList/OneItemBundleList.tsx
Labels: 📬 API

#191 번들 데이터 확인 빌드
  src/components/BundleList/OneItemBundleList.tsx
Labels: 🌏 Deploy

#192 Fix: 이미지 url 특수문자 제거
  src/components/BundleList/OneItemBundleList.tsx
Labels: 🐞 BugFix, 📬 API

#193 Develop
  src/components/BundleList/OneItemBundleList.tsx
Labels: 🐞 BugFix, 📬 API

#194 Fix: 검색창 페이지로 전환 및 버그 수정
  src/app/@modal/_(...)search/modal.tsx
  src/app/@modal/_(...)search/page.tsx
  src/app/search/[searchItem]/page.tsx
  src/app/search/page.tsx
  src/components/AppBar/Search.tsx
  src/components/LoadingSpinner.tsx
  src/components/Toast.tsx
  src/components/products/BottomBtn.tsx
  src/components/products/ProductHeader.tsx
  src/containers/search/AutoSearchData.tsx
  src/containers/search/EventCards.tsx
  src/containers/search/NonSearch.tsx
  src/containers/search/RecentSearch.tsx
  src/containers/search/SearchInputBar.tsx
Labels: 🐞 BugFix

#195 Feature/bug fix
  src/app/(main)/category/[...categoryName]/page.tsx
  src/app/(member)/my-clip/page.tsx
  src/app/(products)/products/[code]/page.tsx
  src/app/(products)/products/[code]/reviews/page.tsx
  src/app/@modal/(...)search/page.tsx
  src/app/@modal/_(...)search/modal.tsx
  src/app/@modal/_(...)search/page.tsx
  src/app/api/auth/[...nextauth]/options.ts
  src/app/search/[searchItem]/page.tsx
  src/app/search/page.tsx
  src/components/AppBar/GoToCart.tsx
  src/components/AppBar/NoticeBtn.tsx
  src/components/AppBar/Search.tsx
  src/components/AppBar/index.tsx
  src/components/BundleList/OneItemBundleList.tsx
  src/components/Buttons/LikeBtn.tsx
  src/components/Filter/AllFilter.tsx
  src/components/Footer/MiniFooter.tsx
  src/components/Join/IdInput.tsx
  src/components/LoadingSpinner.tsx
  src/components/ProductCard/TwoProductCard.tsx
  src/components/ProductsOption/OptionCheck.tsx
  src/components/Toast.tsx
  src/components/products/BottomBtn.tsx
  src/components/products/ProductHeader.tsx
  src/components/products/ReviewSimple.tsx
  src/components/products/ShareModal.tsx
  src/containers/cart/CartHeader.tsx
  src/containers/cart/UserDeliveryAddress.tsx
  src/containers/category/ThemeList.tsx
  src/containers/category/[categoryName]/CategoryMPage.tsx
  src/containers/category/[categoryName]/CategoryNameHeader.tsx
  src/containers/category/[categoryName]/CategorySmall.tsx
  src/containers/join-form/JoinForm.tsx
  src/containers/my-clip/MyLikeFilter.tsx
  src/containers/my-clip/MyLikeItemArea.tsx
  src/containers/my-clip/MyLikeItemList.tsx
  src/containers/my-clip/ProductCard.tsx
  src/containers/myssg/OrderCheck.tsx
  src/containers/myssg/QuickLink.tsx
  src/containers/myssg/UniverseCarousel.tsx
  src/containers/non-login/NonBtn.tsx
  src/containers/order/OrderCards.tsx
  src/containers/ranking/Realtime.tsx
  src/containers/ranking/index.tsx
  src/containers/search/AutoSearchData.tsx
  src/containers/search/EventCards.tsx
  src/containers/search/NonSearch.tsx
  src/containers/search/RecentSearch.tsx
  src/containers/search/SearchInputBar.tsx
  src/utils/getClipApi.ts
Labels: 🐞 BugFix, 📬 API

#197 Fix: 카테고리 좋아요 불러오기
  src/components/products/CategoryPreview.tsx
  src/containers/my-clip/CategoryList.tsx
  src/containers/my-clip/MyLikeFilter.tsx
  src/containers/my-clip/ProductList.tsx
Labels: 🐞 BugFix, 📬 API

#198 Fix: 비회원 장바구니 불러오기 수정
  src/components/AppBar/CartCntForClient.tsx
  src/components/AppBar/GoToCart.tsx
  src/components/Buttons/GetCartBtn.tsx
  src/states/cartAtom.ts
Labels: 🐞 BugFix

#199 Develop
  src/components/AppBar/CartCntForClient.tsx
  src/components/AppBar/GoToCart.tsx
  src/components/Buttons/GetCartBtn.tsx
  src/components/products/CategoryPreview.tsx
  src/containers/my-clip/CategoryList.tsx
  src/containers/my-clip/MyLikeFilter.tsx
  src/containers/my-clip/MyLikeItemEdit.tsx
  src/containers/my-clip/MyLikeItemInfo.tsx
  src/containers/my-clip/ProductCard.tsx
  src/containers/my-clip/ProductList.tsx
  src/states/cartAtom.ts
Labels: 🌏 Deploy

#200 Fix: 비동기 로직 수정
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/isekai-fe.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  src/components/Buttons/GetCartBtn.tsx
  tmp.html
Labels: 🐞 BugFix

#201 Fix: 비동기 로직 수정
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/isekai-fe.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  src/components/Buttons/GetCartBtn.tsx
  tmp.html
Labels: 🐞 BugFix

#202 Fix: 번들 이미지 aspect 지정
  src/components/BundleList/OneItemBundleList.tsx
  src/styles/globals.css
Labels: 🐞 BugFix

#203 Fix: 좋아요 수정
  src/components/BundleList/OneItemBundleList.tsx
  src/containers/my-clip/CategoryList.tsx
  src/containers/my-clip/MyLikeFilter.tsx
  src/containers/my-clip/MyLikeItemInfo.tsx
  src/states/likeAtom.ts
  src/styles/globals.css
  src/types/myClipType.ts
  src/utils/getClipApi.ts
Labels: 🐞 BugFix
